export interface Models {
  model_name: string;
  max_tokens?: number;
  max_input_tokens?: number;
  max_output_tokens?: number;
  input_cost_per_token?: number;
  output_cost_per_token?: number;
  litellm_provider: string;
  mode?:
    | "chat"
    | "completion"
    | "embedding"
    | "moderations"
    | "image_generation"
    | "audio_transcription"
    | "audio_speech";
  supports_function_calling?: boolean;
  supports_parallel_function_calling?: boolean;
  supports_vision?: boolean;
  source?: string;
  output_vector_size?: number;
  input_cost_per_pixel?: number;
  output_cost_per_pixel?: number;
  input_cost_per_second?: number;
  output_cost_per_second?: number;
  input_cost_per_character?: number;
  supports_assistant_prefill?: boolean;
  input_cost_per_token_cache_hit?: number;
  supports_tool_choice?: boolean;
  tool_use_system_prompt_tokens?: number;
  output_cost_per_character?: number;
  input_cost_per_image?: number;
  input_cost_per_video_per_second?: number;
  input_cost_per_audio_per_second?: number;
  input_cost_per_token_above_128k_tokens?: number;
  input_cost_per_character_above_128k_tokens?: number;
  output_cost_per_token_above_128k_tokens?: number;
  output_cost_per_character_above_128k_tokens?: number;
  output_cost_per_image?: number;
  output_cost_per_video_per_second?: number;
  output_cost_per_audio_per_second?: number;
  supports_system_messages?: boolean;
  supports_response_schema?: boolean;
  max_images_per_prompt?: number;
  max_videos_per_prompt?: number;
  max_video_length?: number;
  max_audio_length_hours?: number;
  max_audio_per_prompt?: number;
  max_pdf_size_mb?: number;
  cost_per_image?: number;
  input_cost_per_token_batch_requests?: number;
  input_cost_per_request?: number;
}
